jdevelops:
  jwt:
    expire-time: 100000
    token-secret: c4c33a6f172f13f91500b6c437a78d2cc5e5e9973e7dee431a1e8c34e68d365e
    cookie:
      cookie: true
    verify-platform: true
  swagger:
    base-package: cn.tannn.test.logslogin.controller
knife4j:
  production: false
  enable: true
#springdoc:
#  api-docs:
#    enabled: false
#  swagger-ui:
#    enabled: false
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tb_login?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database: mysql
    show-sql: true
