spring:
  profiles:
    active: api
#logging:
#  level:
#    root: error
#  org.springframework.boot: debug



---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod
jdevelops:
  api:
    log:
      enabled: false


---
spring:
  config:
    activate:
      on-profile: api
jdevelops:
  api:
    log:
      intercept-apis: ["/post/v1","/post/v2"]
